### ISSUE TITLE
WordPress is very slow on Cloud Run

### ISSUE THREAD

**Issue by kientv** [kslifer/wordpress-on-gcp-free-tier#3]
Thanks @kslifer , I have just try to use your Dockerfile, but It's very slow. About 5 to 7 seconds on each requests for both wp-admin & wp frontend (https://apache-57captiswa-as.a.run.app)   

![image](https://user-images.githubusercontent.com/3217438/122053985-73f2f400-ce11-11eb-9f99-ae1c7128af45.png)

![image](https://user-images.githubusercontent.com/3217438/122054024-7e14f280-ce11-11eb-9af8-0007b913549f.png)

I see that your page is very fast: https://kevinslifer.com, Do you know why ?

**Comment by kientv** [comment]
It's because I'm using free tier VM on USA as a database server, and deploy service on Cloud Run Singapore. It's not good for performance (because wordpress using many sql queries).

Thanks

**Comment by kslifer** [comment]
Hey Trần, thanks for the feedback. It's a good observation, that the Cloud Run service and MySQL VM should be co-located in the same region for optimal performance. And the geographic limitation (US only) on the Compute Engine free tier will make this a challenge to run an international site.

That said, if you find that my site (kevinslifer.com) has tolerable performance, it might make sense to run your Cloud Run service in us-east1 with the MySQL VM. The internal Wordpress frontend <-> backend communication will be as fast as possible, and the egress traffic to the requestor will still have the benefit of navigating on Google's backbone until the local POP.
