### ISSUE TITLE
 Media Library is very slowly in grid mode

### ISSUE THREAD

**Issue by kientv** [kslifer/wordpress-on-gcp-free-tier#5]
Do you see that Media Library is very slowly in grid mode when you use gcs plugin (about 19 seconds) ?.
the loading time of the ajax request of the media gallery is very slow even I regenerate thumbnail.

'time curl 'http://localhost/wp-admin/admin-ajax.php' -X POST ...':
real	0m21,264s

user	0m0,020s

sys	0m0,010s  

  
![image](https://user-images.githubusercontent.com/3217438/133955840-e409e0d9-0cf7-4f77-bdee-82dd47dd48f3.png)

**Comment by kslifer** [comment]
Hi @kientv - that's interesting, I don't experience this at all in my install base for this setup. My entire footprint is in us-east4.

Is this consistent behavior? What's your geographic setup?

**Comment by kientv** [comment]
My entire footprint is in us-west1. this is consistent behavior.
front site speed is fine, but browsing media library is very slow in grid mode (though browsing in list mode is OK).

**Comment by kslifer** [comment]
That's interesting... I use grid mode consistently with a few sites that have loads of images, and it's always responsive enough (under 5s). Here's an example:
![image](https://user-images.githubusercontent.com/48484195/134478731-19d4a9f7-1838-40c9-b37b-4fb6165fc15c.png)

When you say you're using "GCS 0.1.6 plugin" - what exactly is that? If it's this (https://github.com/GoogleCloudPlatform/wordpress-plugins/tree/master/gcs-media-plugin), my understanding is that this is an older plugin that has very poor support. I use WP-Stateless (https://wordpress.org/plugins/wp-stateless/).

**Comment by kslifer** [comment]
Closing due to different plugin being used
