### ISSUE TITLE
Connectivity from Cloud Run to MySQL should be encrypted

### ISSUE THREAD

**Issue by kslifer** [kslifer/wordpress-on-gcp-free-tier#9]

**Comment by kientv** [comment]
Do you want to use ssl connection ?

**Comment by kslifer** [comment]
Yes. A colleague pointed out to me that even though the connectivity from Cloud Run to the MySQL DB is hairpinned through Google's network... it's still unencrypted (whoops). And he pointed me to this link for some direction - https://www.monolune.com/how-to-connect-from-wordpress-to-mysql-using-ssl/

Have you done this?

**Comment by kientv** [comment]
> Yes. A colleague pointed out to me that even though the connectivity from Cloud Run to the MySQL DB is hairpinned through Google's network... it's still unencrypted (whoops). And he pointed me to this link for some direction - https://www.monolune.com/how-to-connect-from-wordpress-to-mysql-using-ssl/
> 
> Have you done this?

No, I have not, but I also think about SSL connection or Stunnel
![image](https://user-images.githubusercontent.com/3217438/135094239-21c0daff-2ed3-4ce9-8f4e-ce407275335d.png)

**Comment by kslifer** [comment]
After some investigation - going to close this issue.

Injecting the "define(\'MYSQL_CLIENT_FLAGS\',MYSQLI_CLIENT_SSL)" configuration via the docker file enables TLS encryption of the request/response data, verified through tcpdump.

When removing this configuration, tcpdump can pick up SQL statements and response data, but the DB user password is hashed using caching_sha2_password (at least by default on MySQL 8).

The MYSQLI_CLIENT_SSL configuration is injected by default using this repo install, so encryption is enabled by default.
